/* Content and translations for the Verinoda Labs site (EN/TR). */
'use strict';
const PAGES = ['home', 'verinoda', 'symbiosis', 'benchmarks', 'install', 'contact'];
const SETS = [
  { id: 'graphify_core', total: 37, rows: [['Verinoda', 36, 1], ['Graphify', 7, 0]] },
  { id: 'heldout_repoatlas', total: 33, rows: [['Verinoda', 25, 1], ['raw', 9, 0], ['Graphify', 8, 0]] },
  { id: 'glow_mod', total: 50, rows: [['Verinoda · text', 48, 1], ['Verinoda · JSON', 44, 1], ['Verinoda · analyze', 43, 1], ['raw', 33, 0], ['Graphify', 13, 0]] },
  { id: 'forge_mod', total: 68, rows: [['Verinoda · text', 66, 1], ['Verinoda · JSON', 50, 1], ['Verinoda · analyze', 42, 1], ['raw', 36, 0], ['Graphify', 12, 0]] },
];
const INSTALL = [
  ['uv', 'uv tool install --link-mode copy "verinoda[precise]"'],
  ['pipx', 'pipx install "verinoda[precise]"'],
  ['pip', 'pip install "verinoda[precise]"'],
  ['npx', 'npx -y verinoda --version'],
];
const TERM = [
  ['$ verinoda analyze "How does an order reach the database?"', 'cmd'],
  ['', 'dim'],
  ['claim    create_order_handler → OrderRepository.save', 'txt'],
  ['status   statically_verified', 'ok'],
  ['evidence orders/service.py:22', 'txt'],
  ['', 'dim'],
  ['claim    discount threshold read from config', 'txt'],
  ['status   unknown · next check: verinoda trace', 'warn'],
  ['', 'dim'],
  ['verdict  met_with_inference', 'ok'],
];
const URL_CORE = 'https://github.com/Verinoda-Labs/verinoda';
const URL_SYM = 'https://github.com/Verinoda-Labs/verinoda-symbiosis';

const I18N = {
  en: {
    nav: { verinoda: 'Verinoda', symbiosis: 'Symbiosis', bench: 'Benchmarks', install: 'Install', contact: 'Contact us' },
    home: {
      badge: 'Verinoda 0.4.0 · beta',
      title: 'Coding agents that don’t make things up.',
      lead: 'Verinoda keeps AI coding agents from hallucinating. It maps your codebase in a form agents read naturally, so they get what they ask for more accurately and with far fewer tokens.',
      cta1: 'Talk to us', cta2: 'See benchmarks', termLabel: 'Example session',
      prodKicker: 'Products', prodTitle: 'Two open-source products from Verinoda Labs.',
    },
    stats: [
      { value: '36/37', label: 'gold facts found on Graphify’s own code, at 1,424 tokens per question' },
      { value: '−52%', label: 'tokens per analyze answer, no gold fact lost' },
      { value: '0', label: 'false absents across 126,848 Java sites in a real Minecraft mod' },
      { value: '44', label: 'MCP tools plus a CLI, for Claude Code, Codex and others' },
    ],
    products: {
      verinoda: {
        tag: 'CLI + MCP server', headline: 'Verinoda', card: 'Evidence-first code intelligence. Every answer is a claim with a status and the exact file:line it rests on.', cta: 'Explore Verinoda',
        lead: 'Stops AI coding agents from hallucinating, and gives them a map of your code they can actually use.',
        body: 'Verinoda looks at a repository as a running system: code, call and data flow, tests, configuration, git history and decision records. Questions in English or Turkish come back as claims with evidence. When a claim can’t be supported, it says unknown and names the next check to run.',
        url: URL_CORE, noteTitle: 'Release',
        notes: [
          { k: 'Version', v: '0.4.0 (beta), 2026-10-01' },
          { k: 'Install', v: 'pip, pipx, uv tool or npx' },
          { k: 'Languages', v: 'Python, JS/TS, Java, Kotlin, Go, Rust, C/C++, C# and more' },
          { k: 'License', v: 'Apache-2.0' },
        ],
        featTitle: 'What Verinoda checks for your agent.',
        features: [
          { n: '01', title: 'Claims with evidence', body: 'Each claim carries a status (statically_verified, strong_inference, unknown, stale) and the exact file:line or commit it rests on.' },
          { n: '02', title: 'Name check', body: 'Catches invented APIs in Python, Java, Kotlin and TypeScript imports, with the nearest real name.' },
          { n: '03', title: 'Change review', body: 'For a diff: changed definitions, who depends on them, findings by concern and which tests reach the change.' },
          { n: '04', title: 'Documents and images', body: 'PDF, Word, Excel and PowerPoint files become graph nodes and evidence that can be checked again.' },
          { n: '05', title: 'Decisions stay human', body: '“Which one should we use” questions return a brief and open questions, never a recommendation.' },
          { n: '06', title: 'Notes and 3D graph', body: 'verinoda ui opens a local notes and graph view that follows the index as you edit.' },
        ],
        codeKicker: 'Quick start', codeTitle: 'Index once, then ask.', codeBody: 'Setup indexes the project and connects Claude Code or Codex when they are installed. It is safe to re-run.',
        code: [
          { cmd: 'verinoda setup', note: 'Index + agent skills' },
          { cmd: 'verinoda query "where is the discount threshold configured?"', note: 'Plain-text context for a model' },
          { cmd: 'verinoda trace create_order_handler OrderRepository.save', note: 'Directed paths, each hop with its call site' },
          { cmd: 'verinoda check --diff', note: 'Invented names in the change' },
          { cmd: 'verinoda update .', note: 'Re-index changed files, mark affected claims stale' },
        ],
      },
      symbiosis: {
        tag: 'Verinoda + Claude Code', headline: 'Verinoda Symbiosis', card: 'The same system as a Claude Code mod: more optimized and easier to use, with a live pane and an animated mascot.', cta: 'Explore Symbiosis',
        lead: 'The same system, built into Claude Code: more optimized and easier to use.',
        body: 'Verinoda with verinoda-live, a Claude Code mod that keeps the index fresh while Claude edits, can nudge the agent to use it, reviews commits, and shows it all in a pane with an animated mascot.',
        url: URL_SYM, noteTitle: 'Measured',
        notes: [
          { k: 'Facts', v: 'The same facts with and without the nudge' },
          { k: 'Small corpora', v: 'Fewer tokens' },
          { k: 'Real repos', v: '14% more input tokens' },
          { k: 'Start', v: 'SYMBIOSIS.md, then claude-mods/verinoda-live' },
        ],
        featTitle: 'What the mod adds to Claude Code.',
        features: [
          { n: '01', title: 'Always-fresh index', body: 'Git hooks on commit, checkout, merge and rewrite run verinoda update in the background, so git is never held up.' },
          { n: '02', title: 'Agent nudges', body: 'Puts the index next to Claude’s own searches and reads: definitions, callers and callees of what it looks for.' },
          { n: '03', title: 'Commit review', body: 'Reviews commits as Claude makes them, with the findings in view.' },
          { n: '04', title: 'Live pane and mascot', body: 'A pane inside Claude Code shows index state and reviews, with an animated mascot.' },
          { n: '05', title: 'Answer language', body: '/verinoda-lang auto, tr, en or any language. Sent to the model only when it changes.' },
          { n: '06', title: 'One repository', body: 'The full Verinoda source ships alongside the mod, so both install and update together.' },
        ],
        codeKicker: 'Inside Claude Code', codeTitle: 'Commands the mod brings.', codeBody: 'Start with SYMBIOSIS.md in the repository; the mod lives in claude-mods/verinoda-live.',
        code: [
          { cmd: 'verinoda setup --hooks', note: 'Index plus the git hooks that keep it current' },
          { cmd: '/verinoda', note: 'Ask the index from inside Claude Code' },
          { cmd: '/verinoda-lang tr', note: 'Set the answer language' },
          { cmd: 'verinoda hooks status', note: 'See which hooks are installed' },
        ],
      },
    },
    how: {
      kicker: 'How it works', title: 'From repository to verified claim in four steps.',
      steps: [
        { n: '01', title: 'Index', body: 'One command indexes the code and connects Claude Code or Codex if they are installed.', cmd: 'verinoda setup' },
        { n: '02', title: 'Ask', body: 'Ask in English or Turkish. References are pinned to the exact version you meant.', cmd: 'verinoda analyze "…"' },
        { n: '03', title: 'Read the evidence', body: 'Answers arrive as claims with status, file:line and what is still uncertain.', cmd: 'verinoda claim show clm_…' },
        { n: '04', title: 'Stay current', body: 'After edits, changed files are re-indexed and affected claims are marked stale.', cmd: 'verinoda update .' },
      ],
    },
    bench: {
      kicker: 'Benchmarks', title: 'Published only with their measurement.', factsWord: 'facts',
      lead: 'Each set asks questions with known gold facts and scores whether those facts appear in the context delivered. Compared against Graphify and against reading the files directly.',
      factsTitle: 'Gold facts found', tokTitle: 'Tokens per session', tokNote: 'before the first question', raw: 'Raw reading',
      notes: { graphify_core: '226 files · in-sample', heldout_repoatlas: 'Verinoda’s earlier code', glow_mod: 'Fabric mod · fictional', forge_mod: 'NeoForge · Java + Kotlin' },
      tok: [['Verinoda 0.4', 7330, 1], ['Graphify', 11800, 0], ['Verinoda before', 20500, 0]],
      tokAnalyze: 'analyze per question: 3,901 → 1,873 tokens across eight public sets (86 questions, 319 facts).',
      moreTitle: 'More measurements', colArea: 'Area', colSet: 'Set', colResult: 'Result',
      rows: [
        { a: 'Java name check', s: 'Real Minecraft 26.2 mod', r: '126,848 sites · 0 false absents · 2.3% unknown · 4.7 s · 8/8 planted names caught' },
        { a: 'Python name check', s: '144 generated sites', r: '74 of 74 absent verdicts right · 0 false absents on ~20,800 sites' },
        { a: 'Change review', s: 'Labelled fixtures', r: 'Precision 0.92, recall 62/62 in-sample · 0.81 held-out' },
        { a: 'Honest verdicts', s: 'verdict-audit', r: 'Wrong “met”: 9/23 → 0/23 dev · 8/16 → 1/16 held-out' },
        { a: 'update --fast', s: 'Verinoda’s own repository', r: '3.4 s instead of 27–33 s' },
        { a: 'Turkish questions', s: 'Example app paraphrases', r: '32/32 facts' },
      ],
      method: 'Token counts are chars/4 estimates. No model in the loop: the harness scores whether gold facts are present in the delivered context, not answer accuracy. Some sets are in-sample; see the notes per set.',
    },
    install: {
      kicker: 'Install', title: 'Running in under a minute.',
      lead: 'Verinoda is a Python package with a small npm wrapper. Pick the installer you already use.',
      copy: 'Copy', copied: 'Copied',
      quickTitle: 'First commands',
      quick: [
        { cmd: 'cd my-project && verinoda setup', note: 'Index the code and connect your agents' },
        { cmd: 'verinoda query "where is X configured?"', note: 'The first question indexes a git project by itself' },
        { cmd: 'verinoda ui --graph', note: 'Notes and graph in the browser, local only' },
        { cmd: 'verinoda doctor --brief', note: 'Check the install and index freshness' },
      ],
      reqTitle: 'Requirements',
      reqs: [
        { k: 'Python', v: '3.10+, 3.12+ recommended (the runtime tracer uses sys.monitoring)' },
        { k: 'Platforms', v: 'Tested on Windows 11; CI on Linux, Windows and macOS' },
        { k: 'Agents', v: 'Claude Code, Codex; Cursor, Gemini CLI, Copilot, Kiro and more via setup --agents all' },
        { k: 'Windows', v: 'winget install --id astral-sh.uv -e, then uv tool update-shell' },
      ],
    },
    contact: {
      kicker: 'Contact', title: 'Let’s talk about your codebase.',
      lead: 'Tell us what you are building and where your agents get stuck. We read every message.',
      reasons: [
        { k: 'Teams and enterprise', v: 'Rolling Verinoda out across repositories and agents.' },
        { k: 'Partnerships', v: 'Integrating evidence-first answers into your tools.' },
        { k: 'Press and research', v: 'Benchmarks, methodology and raw logs.' },
      ],
      topic: 'Topic', topics: ['Enterprise', 'Partnership', 'Press', 'Other'],
      name: 'Name', company: 'Company', email: 'Work email', message: 'Message', send: 'Send message',
      errEmail: 'Please enter a valid email address.', errMsg: 'Please write a short message.',
      thanksTitle: 'One more step.', thanksBody: 'We opened a pre-filled message in a new tab. Submit it there and it reaches us.', again: 'Send another',
    },
    cta: { title: 'Bring evidence to your agents.', body: 'Both products are open source and in beta. Talk to us about using them across your team.' },
    footer: 'Verinoda is derived from Graphify (Apache-2.0) and is an independent project, not an official Graphify release.',
  },
  tr: {
    nav: { verinoda: 'Verinoda', symbiosis: 'Symbiosis', bench: 'Benchmark', install: 'Kurulum', contact: 'İletişime geç' },
    home: {
      badge: 'Verinoda 0.4.0 · beta',
      title: 'Uydurmayan kodlama ajanları.',
      lead: 'Verinoda, yapay zekâ kodlama ajanlarının halüsinasyon görmesini engeller. Kodunuzu ajanların doğal olarak okuyacağı biçimde haritalandırır; istedikleri bilgiye çok daha isabetli ve çok daha az token’la ulaşırlar.',
      cta1: 'Bizimle konuşun', cta2: 'Benchmark sonuçları', termLabel: 'Örnek oturum',
      prodKicker: 'Ürünler', prodTitle: 'Verinoda Labs’ten iki açık kaynak ürün.',
    },
    stats: [
      { value: '36/37', label: 'Graphify’nin kendi kodunda bulunan altın bilgi, soru başına 1.424 token' },
      { value: '−52%', label: 'analyze cevabı başına token, hiçbir altın bilgi kaybı olmadan' },
      { value: '0', label: 'gerçek bir Minecraft modunda 126.848 Java noktasında yanlış “absent”' },
      { value: '44', label: 'MCP aracı ve CLI; Claude Code, Codex ve diğerleri için' },
    ],
    products: {
      verinoda: {
        tag: 'CLI + MCP sunucusu', headline: 'Verinoda', card: 'Kanıt öncelikli kod zekâsı. Her cevap; durumu ve dayandığı tam file:line bilgisiyle bir iddiadır.', cta: 'Verinoda’yı incele',
        lead: 'Yapay zekâ kodlama ajanlarının halüsinasyon görmesini engeller ve onlara kodunuzun gerçekten kullanabilecekleri bir haritasını verir.',
        body: 'Verinoda bir depoya çalışan bir sistem gibi bakar: kod, çağrı ve veri akışı, testler, yapılandırma, git geçmişi ve karar kayıtları. İngilizce ya da Türkçe sorular kanıtlı iddialar olarak döner. Desteklenemeyen bir iddia için “unknown” der ve çalıştırılacak bir sonraki kontrolü söyler.',
        url: URL_CORE, noteTitle: 'Sürüm',
        notes: [
          { k: 'Sürüm', v: '0.4.0 (beta), 2026-10-01' },
          { k: 'Kurulum', v: 'pip, pipx, uv tool veya npx' },
          { k: 'Diller', v: 'Python, JS/TS, Java, Kotlin, Go, Rust, C/C++, C# ve daha fazlası' },
          { k: 'Lisans', v: 'Apache-2.0' },
        ],
        featTitle: 'Verinoda ajanınız için neleri kontrol eder.',
        features: [
          { n: '01', title: 'Kanıtlı iddialar', body: 'Her iddia bir durum (statically_verified, strong_inference, unknown, stale) ve dayandığı tam file:line ya da commit taşır.' },
          { n: '02', title: 'İsim kontrolü', body: 'Python, Java, Kotlin ve TypeScript import’larında uydurulmuş API’leri en yakın gerçek isimle yakalar.' },
          { n: '03', title: 'Değişiklik incelemesi', body: 'Bir diff için: değişen tanımlar, onlara bağlı olanlar, konuya göre bulgular ve değişikliğe ulaşan testler.' },
          { n: '04', title: 'Belgeler ve görseller', body: 'PDF, Word, Excel ve PowerPoint dosyaları graf düğümü ve yeniden kontrol edilebilir kanıt olur.' },
          { n: '05', title: 'Kararlar insanda kalır', body: '“Hangisini kullanalım” soruları öneri değil; bir özet ve açık sorularla döner.' },
          { n: '06', title: 'Notlar ve 3D graf', body: 'verinoda ui, düzenledikçe indeksi takip eden yerel bir not ve graf görünümü açar.' },
        ],
        codeKicker: 'Hızlı başlangıç', codeTitle: 'Bir kez indeksleyin, sonra sorun.', codeBody: 'Setup projeyi indeksler ve kuruluysa Claude Code ya da Codex’i bağlar. Tekrar çalıştırmak güvenlidir.',
        code: [
          { cmd: 'verinoda setup', note: 'İndeks + ajan becerileri' },
          { cmd: 'verinoda query "where is the discount threshold configured?"', note: 'Model için düz metin bağlam' },
          { cmd: 'verinoda trace create_order_handler OrderRepository.save', note: 'Yönlü yollar, her adım çağrı noktasıyla' },
          { cmd: 'verinoda check --diff', note: 'Değişiklikteki uydurulmuş isimler' },
          { cmd: 'verinoda update .', note: 'Değişen dosyaları yeniden indeksle, etkilenen iddiaları stale işaretle' },
        ],
      },
      symbiosis: {
        tag: 'Verinoda + Claude Code', headline: 'Verinoda Symbiosis', card: 'Aynı sistemin Claude Code modlarıyla daha optimize ve kolaylaştırılmış hâli; canlı panel ve animasyonlu maskotla.', cta: 'Symbiosis’i incele',
        lead: 'Aynı sistem, Claude Code’un içinde: daha optimize ve kullanımı daha kolay.',
        body: 'Verinoda ile verinoda-live bir arada: Claude düzenleme yaparken indeksi güncel tutan, ajanı indeksi kullanmaya yönlendirebilen, commit’leri inceleyen ve hepsini animasyonlu bir maskotla bir panelde gösteren Claude Code modu.',
        url: URL_SYM, noteTitle: 'Ölçülen',
        notes: [
          { k: 'Bilgi', v: 'Yönlendirmeyle ve yönlendirmesiz aynı bilgiler' },
          { k: 'Küçük derlem', v: 'Daha az token' },
          { k: 'Gerçek depo', v: '%14 daha fazla girdi token’ı' },
          { k: 'Başlangıç', v: 'SYMBIOSIS.md, ardından claude-mods/verinoda-live' },
        ],
        featTitle: 'Mod, Claude Code’a neler katar.',
        features: [
          { n: '01', title: 'Hep güncel indeks', body: 'Commit, checkout, merge ve rewrite git hook’ları verinoda update’i arka planda çalıştırır; git hiç bekletilmez.' },
          { n: '02', title: 'Ajan yönlendirme', body: 'Claude’un kendi arama ve okumalarının yanına indeksi koyar: aradığı şeyin tanımı, çağıranları ve çağırdıkları.' },
          { n: '03', title: 'Commit incelemesi', body: 'Claude commit yaptıkça inceler, bulgular gözünüzün önünde kalır.' },
          { n: '04', title: 'Canlı panel ve maskot', body: 'Claude Code içindeki bir panel indeks durumunu ve incelemeleri animasyonlu bir maskotla gösterir.' },
          { n: '05', title: 'Cevap dili', body: '/verinoda-lang auto, tr, en ya da herhangi bir dil. Modele yalnızca değiştiğinde gönderilir.' },
          { n: '06', title: 'Tek depo', body: 'Tam Verinoda kaynağı modla birlikte gelir; ikisi birlikte kurulur ve güncellenir.' },
        ],
        codeKicker: 'Claude Code içinde', codeTitle: 'Modun getirdiği komutlar.', codeBody: 'Depodaki SYMBIOSIS.md ile başlayın; mod claude-mods/verinoda-live klasöründedir.',
        code: [
          { cmd: 'verinoda setup --hooks', note: 'İndeks ve onu güncel tutan git hook’ları' },
          { cmd: '/verinoda', note: 'Claude Code içinden indekse sorun' },
          { cmd: '/verinoda-lang tr', note: 'Cevap dilini ayarlayın' },
          { cmd: 'verinoda hooks status', note: 'Hangi hook’ların kurulu olduğunu görün' },
        ],
      },
    },
    how: {
      kicker: 'Nasıl çalışır', title: 'Depodan doğrulanmış iddiaya dört adımda.',
      steps: [
        { n: '01', title: 'İndeksle', body: 'Tek komut kodu indeksler; kuruluysa Claude Code veya Codex’i bağlar.', cmd: 'verinoda setup' },
        { n: '02', title: 'Sor', body: 'İngilizce ya da Türkçe sorun. Referanslar kastettiğiniz tam sürüme sabitlenir.', cmd: 'verinoda analyze "…"' },
        { n: '03', title: 'Kanıtı oku', body: 'Cevaplar durum, file:line ve hâlâ belirsiz olanlarla birlikte iddia olarak gelir.', cmd: 'verinoda claim show clm_…' },
        { n: '04', title: 'Güncel kal', body: 'Düzenlemelerden sonra değişen dosyalar yeniden indekslenir, etkilenen iddialar stale işaretlenir.', cmd: 'verinoda update .' },
      ],
    },
    bench: {
      kicker: 'Benchmark', title: 'Yalnızca ölçümüyle birlikte yayımlanır.', factsWord: 'bilgi',
      lead: 'Her set, altın bilgisi bilinen sorular sorar ve bu bilgilerin teslim edilen bağlamda yer alıp almadığını puanlar. Graphify ve dosyaları doğrudan okumayla karşılaştırılır.',
      factsTitle: 'Bulunan altın bilgi', tokTitle: 'Oturum başına token', tokNote: 'ilk sorudan önce', raw: 'Doğrudan okuma',
      notes: { graphify_core: '226 dosya · örneklem içi', heldout_repoatlas: 'Verinoda’nın eski kodu', glow_mod: 'Fabric modu · kurgusal', forge_mod: 'NeoForge · Java + Kotlin' },
      tok: [['Verinoda 0.4', 7330, 1], ['Graphify', 11800, 0], ['Verinoda önceki', 20500, 0]],
      tokAnalyze: 'soru başına analyze: sekiz açık sette (86 soru, 319 bilgi) 3.901 → 1.873 token.',
      moreTitle: 'Diğer ölçümler', colArea: 'Alan', colSet: 'Set', colResult: 'Sonuç',
      rows: [
        { a: 'Java isim kontrolü', s: 'Gerçek Minecraft 26.2 modu', r: '126.848 nokta · 0 yanlış absent · %2,3 unknown · 4,7 sn · 8/8 yerleştirilmiş isim yakalandı' },
        { a: 'Python isim kontrolü', s: '144 üretilmiş nokta', r: '74 absent kararının 74’ü doğru · ~20.800 noktada 0 yanlış absent' },
        { a: 'Değişiklik incelemesi', s: 'Etiketli fikstürler', r: 'Kesinlik 0,92, duyarlılık 62/62 örneklem içi · ayrılmış sette 0,81' },
        { a: 'Dürüst kararlar', s: 'verdict-audit', r: 'Yanlış “met”: 9/23 → 0/23 dev · 8/16 → 1/16 ayrılmış set' },
        { a: 'update --fast', s: 'Verinoda’nın kendi deposu', r: '27–33 sn yerine 3,4 sn' },
        { a: 'Türkçe sorular', s: 'Örnek uygulama açıklamaları', r: '32/32 bilgi' },
      ],
      method: 'Token sayıları karakter/4 tahminidir. Döngüde model yoktur: ölçüm, cevap doğruluğunu değil altın bilgilerin teslim edilen bağlamda bulunup bulunmadığını puanlar. Bazı setler örneklem içidir; set notlarına bakın.',
    },
    install: {
      kicker: 'Kurulum', title: 'Bir dakikadan kısa sürede çalışır.',
      lead: 'Verinoda, küçük bir npm sarmalayıcısı olan bir Python paketidir. Zaten kullandığınız kurucuyu seçin.',
      copy: 'Kopyala', copied: 'Kopyalandı',
      quickTitle: 'İlk komutlar',
      quick: [
        { cmd: 'cd my-project && verinoda setup', note: 'Kodu indeksleyin ve ajanlarınızı bağlayın' },
        { cmd: 'verinoda query "where is X configured?"', note: 'İlk soru bir git projesini kendiliğinden indeksler' },
        { cmd: 'verinoda ui --graph', note: 'Tarayıcıda notlar ve graf, yalnızca yerel' },
        { cmd: 'verinoda doctor --brief', note: 'Kurulumu ve indeksin güncelliğini kontrol edin' },
      ],
      reqTitle: 'Gereksinimler',
      reqs: [
        { k: 'Python', v: '3.10+, önerilen 3.12+ (çalışma zamanı izleyicisi sys.monitoring kullanır)' },
        { k: 'Platformlar', v: 'Windows 11’de test edildi; CI Linux, Windows ve macOS’ta' },
        { k: 'Ajanlar', v: 'Claude Code, Codex; setup --agents all ile Cursor, Gemini CLI, Copilot, Kiro ve diğerleri' },
        { k: 'Windows', v: 'winget install --id astral-sh.uv -e, ardından uv tool update-shell' },
      ],
    },
    contact: {
      kicker: 'İletişim', title: 'Kod tabanınızı konuşalım.',
      lead: 'Ne geliştirdiğinizi ve ajanlarınızın nerede takıldığını anlatın. Her mesajı okuyoruz.',
      reasons: [
        { k: 'Ekipler ve kurumlar', v: 'Verinoda’yı depolar ve ajanlar genelinde yaygınlaştırmak.' },
        { k: 'İş ortaklıkları', v: 'Kanıt öncelikli cevapları kendi araçlarınıza entegre etmek.' },
        { k: 'Basın ve araştırma', v: 'Benchmark’lar, yöntem ve ham kayıtlar.' },
      ],
      topic: 'Konu', topics: ['Kurumsal', 'İş ortaklığı', 'Basın', 'Diğer'],
      name: 'Ad Soyad', company: 'Şirket', email: 'İş e-postası', message: 'Mesaj', send: 'Mesajı gönder',
      errEmail: 'Lütfen geçerli bir e-posta adresi girin.', errMsg: 'Lütfen kısa bir mesaj yazın.',
      thanksTitle: 'Bir adım kaldı.', thanksBody: 'Hazır doldurulmuş bir mesajı yeni sekmede açtık. Orada göndermeniz yeterli.', again: 'Yeni mesaj gönder',
    },
    cta: { title: 'Ajanlarınıza kanıt getirin.', body: 'İki ürün de açık kaynak ve beta aşamasında. Ekibinizde kullanmak için bizimle konuşun.' },
    footer: 'Verinoda, Graphify’den (Apache-2.0) türetilmiş bağımsız bir projedir; resmi bir Graphify sürümü değildir.',
  },
};
